// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzs-CSs5_zXqCbSEZ-r6fnZ6iDq9PamqI',
    appId: '1:229361370387:web:62e7e7bd7cde472a1b86e6',
    messagingSenderId: '229361370387',
    projectId: 'login-screen-65942',
    authDomain: 'login-screen-65942.firebaseapp.com',
    storageBucket: 'login-screen-65942.appspot.com',
    measurementId: 'G-2N7P3KJ2ND',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKzK_xIJBwecXcQ-NzG-L86nk3cV5fih0',
    appId: '1:229361370387:android:c50fa19189079d1d1b86e6',
    messagingSenderId: '229361370387',
    projectId: 'login-screen-65942',
    storageBucket: 'login-screen-65942.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjkoxcjs9lxnsKxxfWh2orPEXTVY0EaCg',
    appId: '1:229361370387:ios:f51a743ed2c245c31b86e6',
    messagingSenderId: '229361370387',
    projectId: 'login-screen-65942',
    storageBucket: 'login-screen-65942.appspot.com',
    iosClientId: '229361370387-otkjer1ac40dcn2a241vdcecnn0a18ke.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginBackend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjkoxcjs9lxnsKxxfWh2orPEXTVY0EaCg',
    appId: '1:229361370387:ios:f51a743ed2c245c31b86e6',
    messagingSenderId: '229361370387',
    projectId: 'login-screen-65942',
    storageBucket: 'login-screen-65942.appspot.com',
    iosClientId: '229361370387-otkjer1ac40dcn2a241vdcecnn0a18ke.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginBackend',
  );
}
